[helpers]

[default]
depends = []

[default.files]
mpv = "~/scoop/persist/mpv/portable_config/"
"nushell/windows/config.nu" = "~/AppData/Roaming/nushell/config.nu"
"nushell/windows/env.nu" = "~/AppData/Roaming/nushell/env.nu"
"nushell/aws_lib.nu" = "~/AppData/Roaming/nushell/aws_lib.nu"
"nushell/lazyglue.nu" = "~/AppData/Roaming/nushell/lazyglue.nu"
nvim = "~/AppData/Local/nvim/"
pgcli = "~/AppData/Local/dbcli/pgcli/"
starship = "~/.config/"
wezterm = "~"
yazi = "~/AppData/Roaming/yazi/config/"

[default.variables]

[linux]
depends = []

[linux.files]
"nushell/nix/config.nu" = "~/.config/nushell/config.nu"
"nushell/nix/env.nu" = "~/.config/nushell/env.nu"
"nushell/aws_lib.nu" = "~/.config/nushell/aws_lib.nu"
"nushell/lazyglue.nu" = "~/.config/nushell/lazyglue.nu"
nvim = "~/.config/nvim/"
pgcli = "~/.config/pgcli/"
starship = "~/.config/"
yazi = "~/.config/yazi/"

[linux.variables]

[settings]
default_target_type = "automatic"

